# This file indicates the versions of libraries used in the build process
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
picocli = "4.7.7"
caffeine = "3.2.0"
gson = "2.13.1"
guava = "33.4.8-jre"
leveldb = "1.0.1"
leveldb-api = "1.0.1"
fastutil = "8.5.15"
lz4 = "1.3.0"
jetbrains-annotations = "26.0.2"

# JUnit
junit = "5.13.0"

# Plugins
shadow = "8.3.6"
gitVersion = "3.3.0"
jpackage = "1.6.1"
node = "7.1.0"

[libraries]
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
leveldb = { module = "com.hivemc.leveldb:leveldb", version.ref = "leveldb" }
leveldb-api = { module = "com.hivemc.leveldb:leveldb-api", version.ref = "leveldb-api" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
lz4 = { module = "net.jpountz.lz4:lz4", version.ref = "lz4" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
gitVersion = { id = "com.palantir.git-version", version.ref = "gitVersion" }
jpackage = { id = "org.panteleyev.jpackageplugin", version.ref = "jpackage" }
node = { id = "com.github.node-gradle.node", version.ref = "node" }
